name: Provision Robo infra
on: [workflow_dispatch]
jobs:
  DEV-PLAN:
   runs-on: self-hosted
   steps:
     - uses: actions/checkout@v4 #code checkout
     - name: Terraform  init
       run: terraform init -backend-config=env-dev/state.tfvars
     - name: Terraform plan
       run: terraform plan -var-file=env-dev/main.tfvars
  DEV-APPLY:
   runs-on: self-hosted
   environment: dev
   needs: DEV-PLAN
   steps:
     - uses: actions/checkout@v4 #code checkout
     - name: Terraform  init
       run: terraform init -backend-config=env-dev/state.tfvars
     - name: Terraform apply
       run: terraform apply -var-file=env-dev/main.tfvars -auto-approve
     
  QA:
   runs-on: ubuntu-latest
   environment: qa
   needs: DEV-APPLY
   steps:
     
     - run: echo Dummy job
  UAT:
   runs-on: ubuntu-latest
   environment: uat
   needs: QA
   steps:
     
     - run: echo Dummy job
  PROD:
   runs-on: self-hosted
   environment: prod
   needs: PROD
   steps:
     
     - uses: actions/checkout@v4 #code checkout
     - name: Terraform  init
       run: terraform init -backend-config=env-prod/state.tfvars